import type { NextPage } from 'next'
import Head from 'next/head'
import { Hero } from '@sections/homePage/hero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SalesAssist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className='h-screen px-4 container mx-auto'>
        <h1>hello</h1>
      </main>

      <section className='h-screen px-4 bg-gray-primary'>
        <div className=' container mx-auto'>
          <h2>section</h2>
        </div>
      </section>

      <section className='h-[60vh] px-4 flex flex-col relative'>
        <div className="bg-gray-primary absolute inset-0 clip"></div>
      </section>

      <section className='h-60 px-4 flex flex-col relative'>
      </section>

      <footer className='bg-white-normal'>
          <div className='p-12 container mx-auto'>
              <h2>footer</h2>
          </div>
      </footer>
    </>
  )
}

export default Home
