import type { NextPage } from 'next'
import Head from 'next/head'
import { Hero } from '@src/sections/homePage/Cover';
import { HowItWorks } from '@src/sections/homePage/HowItWorks';
import { Benefits } from '@src/sections/homePage/Benefits';
import { SalesTeams } from '@src/sections/homePage/SalesTeams';
import { Sales } from '@src/sections/homePage/Sales';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SalesAssist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <HowItWorks/>

      <Benefits />

      <SalesTeams />

      <Sales />
    </>
  )
}

export default Home
